network/ipfs_impl.go

Let's not split every wantlist into a length and a wantlist...

buffer writes

---

bitswap.go
decision/engine.go
decision/peer_request_queue.go
message/message.go
messagequeue/messagequeue.go
network/interface.go
network/ipfs_impl.go
peermanager/peermanager.go
session.go
sessionmanager/sessionmanager.go
testnet/internet_latency_delay_generator.go
testnet/virtual.go
testutil/testutil.go
wantlist/wantlist.go
wantmanager/wantmanager.go

per https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences
in response to https://github.com/ipfs/go-bitswap/pull/29#discussion_r239287566

docs(comments): end comment sentences to have full-stop

---

workers.go

Fixes https://github.com/ipfs/go-bitswap/issues/35 and https://github.com/ipfs/go-bitswap/issues/36.

Fix debug log formatting issues

---

bitswap.go

fix(bitswap): remove CancelWants function

---

messagequeue/messagequeue.go

This is embarassing, but when https://github.com/ipfs/go-bitswap/pull/94 got merged I left about 10 lines of code in messagequeue.go doing nothing and discovered this today.

refactor(messagequeue): remove dead code

---

README.md

One of my tasks this quarter is to get a lead maintainer for each repo.
See: https://github.com/ipfs/team-mgmt/blob/master/LEAD_MAINTAINER_PROTOCOL.md

doc: add dirk as the lead maintainer

---

decision/decision.go

Fixes https://github.com/ipfs/go-bitswap/issues/267

Expose decision.Receipt externally

---

internal/decision/engine_test.go

Fixes https://github.com/ipfs/go-bitswap/issues/285

Fix flaky engine peer tagging test

---

internal/messagequeue/donthavetimeoutmgr_test.go

Fixes https://github.com/ipfs/go-bitswap/issues/292

fix flaky TestDontHaveTimeoutMgrTimeout

---

internal/decision/engine.go
internal/decision/engine_test.go

Fixes https://github.com/ipfs/go-bitswap/issues/295

Fix engine test TestTaggingUseful

---

network/ipfs_impl.go

fix: 64bit align stats

---

message/pb/cid_test.go

This got dropped from my other patch.

test(message): test custom CID type

---

internal/messagequeue/donthavetimeoutmgr_test.go

Fixes https://github.com/ipfs/go-bitswap/issues/318

fix: flaky TestDontHaveTimeoutMgrTimeout

---

internal/decision/engine_test.go

Fixes https://github.com/ipfs/go-bitswap/issues/319

fix: flaky TestSendDontHave

---

internal/peermanager/peermanager.go
internal/peermanager/peerwantmanager.go
internal/peermanager/peerwantmanager_test.go
internal/wantmanager/wantmanager.go

This makes it easier to tell where module boundaries are.

chore: make pwm internals private

---

internal/sessioninterestmanager/sessioninterestmanager.go

Fixes https://github.com/ipfs/go-bitswap/issues/313
`SessionWantList` has its own internal locking, so it would be more efficient to use a custom data structure for `SessionInterestManager` rather than using two `SessionWantList`s. However I would prefer to go with this solution for now as it's a simpler change, and revisit if there's a performance issue.

fix: race in SessionInterestManager

---

go.sum
internal/messagequeue/messagequeue.go

Instead of copying these slices, we can just reuse them.

feat: optimize message sending

---

internal/messagequeue/messagequeue.go

Fixes https://github.com/ipfs/go-bitswap/issues/347

fix: mark wants sent when they are added to a message to be sent

---

internal/peermanager/peerwantmanager.go

Instead of tracking offsets, just create a "new" slice starting with the broadcast cancel slice. Under the covers, this will just use the same memory over and over.

feat: simplify broadcast cancel logic

---

go.mod
go.sum
internal/decision/engine.go
internal/decision/engine_test.go

Quick alternative to #407 to fix the main issue.

fix: only track useful received data in the ledger

---

internal/decision/blockstoremanager_test.go

It's still timing dependent, but we have a 2.5x timeout increase.

fix: make blockstore cancel test less timing dependent

---

README.md

NewFromIPFSHost -> NewFromIpfsHost

Change incorrect function name in README

---

version.json

Coalesce connection state events to prevent goroutine buildup.

chore: release v0.6.1
