decision/bench_test.go
decision/engine.go
decision/engine_test.go
decision/peer_request_queue.go
decision/peer_request_queue_test.go
package.json
wantlist/wantlist.go
wantmanager.go
workers.go

Updated PeerRequestTask to hold multiple wantlist.Entry(s). This allows Bitswap to send multiple blocks in bulk per a Peer's request. Also, added a metric for how many blocks to put in a given message. Currently: 512 * 1024 bytes. 
Fixes [#4378](https://github.com/ipfs/go-ipfs/issues/4378)
@whyrusleeping @Stebalien

bitswap: Bitswap now sends multiple blocks per message

---

decision/engine.go
decision/peer_request_queue.go
message/message.go
message/message_test.go
message/pb/Makefile
message/pb/message.pb.go
message/pb/message.proto
session.go
wantlist/wantlist.go

1. Change the protobuf code generation to reduce allocations. We get a lot of wantlists.
2. Avoid allocating task keys.

reduce allocations

---

dup_blocks_test.go
testnet/internet_latency_delay_generator.go
testnet/internet_latency_delay_generator_test.go
testnet/virtual.go

Build a benchmark that can replicate the problems that #8 has with LS-ing Wikipedia
- add a delay generator that similates real world latencies one might encounter on the internet
- modify virtual network to accept different latencies for different
peers based on using NextWaitTime on passed delay
- modify dup_blocks_test subtestDistributeAndFetch to accept a custom
delay
- Add a real world benchmarks that simulates the kinds of problems one might
encounter bitswaping with a long lived session and a large swarm of
peers with real world latency distributions (that causes #8 not to
function well in practice)
The goal here is to have a good benchmark to compare against as we continue to develop improvements to bitswap.
One thing not addressed here are transfer speeds (though you can think of …

feat(Benchmarks): Add real world dup blocks test

---

bitswap.go
bitswap_test.go

If Bitswap receives a block that isn't in it's wantlist, is should ignore it, and not add it to the block store
Blocks get received in bitswap one of two ways. They're either added by the user (HasBlock) -- and in this case it seems like they should always get added to the blockstore. Or, they come in through the network -- through the ReceiveMessage function. It seems to me, and it's possible I'm missing something, this is the place to ignore an unwanted block. This perhaps naive implementation simply checks blocks received from the network against the global wantlist and ignores them if they aren't in the wantlist.
There are interesting questions about what exactly we want to do and not do with an unwanted block. This approach counts the block in statistics but doesn't provide it, add …

fix(Receiver): Ignore unwanted blocks

---

bitswap.go
bitswap_test.go
messagequeue/messagequeue.go
messagequeue/messagequeue_test.go
peermanager/peermanager.go
peermanager/peermanager_test.go
testutil/testutil.go
wantmanager/wantmanager.go
wantmanager/wantmanager_test.go
workers.go

Modularize Bitswap in preparation for attempts to optimize bitswap further
child of #26 
- Seperated out a PeerManager, which was part of WantManager but doesn't seem at all tied to managing peers
- Made unit tests for PeerManager and WantManager
- Discovered issues while unit testing with synchronization of calls that lead to unpredictable output and refactored both classes to process messages serially to provide a predictable interface (apologies for bringing in erlang like actor pattern habits of using message passing)
- Moved SendBlocks function which seemed like a one off that had little to do with WantManager back in main bitswap package for now
- Comment remaining public interfaces

Bitswap Refactor #2: Extract PeerManager From Want Manager + Unit Test

---

bitswap.go
session/cidqueue.go
session/session.go
session/session_test.go
sessionmanager/sessionmanager.go
sessionmanager/sessionmanager_test.go
sessionpeermanager/sessionpeermanager.go
sessionpeermanager/sessionpeermanager_test.go
testutil/testutil.go

Modularize Bitswap in preparation for attempts to optimize bitswap further
This also gets us quite a bit of the way toward the proposed split of bitswap into low level "just ask for blocks from peers and respond to requests" bitswap and high level bitswap -- sessions, and possibly other drivers as time goes on.
Final PR includes:
- Extracted out the managing of peers for a session into it's own backage -- this way, tracking optimal peers is seperate from improving algorithms for fetch blocks
- Commented all exported functions to 
- Unit test new session manager, new session peermanager
- Unit test sessions (they are currently really more integration tested in the main package)
child of https://github.com/ipfs/go-ipfs/issues/5723

Bitswap Refactor #4: Extract session peer manager from sessions

---

session/session_test.go
sessionpeermanager/sessionpeermanager_test.go

fix #43 
Stop relying on timeouts for concurrency and use go sync primitives

fix(tests): stabilize unreliable session tests

---

bitswap.go
session/session.go
session/session_test.go
sessionmanager/sessionmanager.go
sessionmanager/sessionmanager_test.go
sessionpeermanager/sessionpeermanager.go
sessionpeermanager/sessionpeermanager_test.go
sessionrequestsplitter/sessionrequestsplitter.go
sessionrequestsplitter/sessionrequestsplitter_test.go

This is an initial PR to speed up sessions and reduce dupes. It is not the ONLY improvement I'm working on, but it makes significant progress. It matches Jeremy's PR on benchmarks for dupes (for the most part), but matches master on speed (for the most part). In addition, it shows impressive results with `LS` on Wikipedia. See results in comments.
This PR has basically 3 improvements:
1. The session peer manager is just SLIGHTLY smarter in that:
a. It returns a maximum of 32 peers (why would you ever need to ask more at once?)
b. It somewhat prioritizes the best peers. The strategy is simply if you receive a block from a peer first, you assume that's a good peer and put it at the front of the list for peers on your next want request. This is not ordering peers by latency, it's just …

Speed up sessions Round #1

---

bitswap_with_sessions_test.go
session/session.go
sessionpeermanager/sessionpeermanager.go
sessionpeermanager/sessionpeermanager_test.go

When providers are found in a session, explicitly connect them so they get added to the peer manager
fix #53
- For now, copy the code that is used by the providerQueryWorker to connect newly found providers (this will be removed when we address #52)
- Add a test which demonstrates the failing case for this behavior (fetching blocks from a peer that is not already connected), and verify changes resolve it
n/a

fix(sessions): explicitly connect found peers

---

peermanager/peermanager.go
sessionpeermanager/sessionpeermanager.go
sessionrequestsplitter/sessionrequestsplitter.go
wantmanager/wantmanager.go
workers.go

Also, buffer single-use channels we may walk away from. This was showing up (rarely) in a go-ipfs test (test/integration.Test1KBInstantaneous).

contexts: make sure to abort when a context is canceled

---

session/session_test.go
sessionpeermanager/sessionpeermanager_test.go

Improve stability of tests for Session and SessionPeerManager so that CI consistently passes
Basically, tests of concurrent code is hard. Definitely don't want to deadlock, and also, want to make sure synchronization is correct so that work is always done before results are tests
With that in mind:
- make channel read/writes select statements
- Change ordering for channel reads in TestSessionFindMorePeers -- this was the issue -- the cancel wants channel is actually the first thing that needs to be read. And, additional fix for Windows where apparently timing is very imprecise. (https://github.com/golang/go/issues/29714)
- Additional channels and syncing for SessionPeerManager tests -- not that much of the complexity here goes away when #60 is merged, and is indicative of the current code …

fix(tests): stabilize session tests

---

bitswap.go
providerquerymanager/providerquerymanager.go
providerquerymanager/providerquerymanager_test.go
sessionpeermanager/sessionpeermanager.go
sessionpeermanager/sessionpeermanager_test.go

Build a robust provider finder for sessions so that we can deduplicate provider logic (#52) and soon merge GetBlock w/ Session.GetBlocks (#49)
A manager for find provider requests that:
- dedups requests
- rate limits requests
- manages timeouts
- handles connecting to peers once they are found
Will writeup general concurrency architecture tomorrow

Feat: A more robust provider finder for sessions (for now) and soon for all bitswap

---

bitswap.go
bitswap_test.go
workers.go

Simplify Bitswap!
- Just have non-session GetBlocks make a temporary session and use that to get blocks
- Remove all the code you can remove as a result
This is PR'd against enhance-session-provider because it's neccesary to make this all work.
The order is: 
feat/stabilize-tests -> 
feat/enhance-session-provider -> 
feat->merge-get-blocks
fix #52 fix #49

refactor(GetBlocks): Merge session/non-session

---

network/ipfs_impl.go

We now do exactly what the comment is warning about: track peers providing keys.
NOTE: This should be tested against the live network.

providers: don't add every connected node as a provider

---

.travis.yml
Makefile

ci: add travis

---

bitswap.go
bitswap_test.go
bitswap_with_sessions_test.go
notifications/notifications.go
notifications/notifications_test.go
sessionpeermanager/sessionpeermanager_test.go

* fix pubsub race: Calling `wg.Add` after `wg.Wait` has returned is invalid. This change swaps the wait group for a plain rwmutex.
* fix Stat race: mixing atomics with locks doesn't work.
* fix race detector.
(caught with the race detector)

fix multiple data races

---

bitswap.go
messagequeue/messagequeue.go
messagequeue/messagequeue_test.go
peermanager/peermanager.go
peermanager/peermanager_test.go
wantmanager/wantmanager.go
wantmanager/wantmanager_test.go

fix race conditions while setting up wantlists 
This change essentially solves bugs in initial wantlist handling using the strategy outlined by @Stebalien in #51. 
This means two differences:
- Have WantManager handle connect/disconnects and forward to the peer manager
- In the case the peer manager accidentally receives a request to send a message to a peer it's not connected to, create a "temporary peer" queue on demand, which will automatically initiate the connection when it opens a message stream to send a message
- This means to send a message we need the broadcast want list just in case
Other notable changes:
- Remove the go routine from the PeerManager, since basically all it's doing is managing a map
- Add a retry limit to peer message queues, cause we might be connecting to less …

fix(wantlist): remove races on setup

---

bitswap.go
decision/peer_request_queue.go
messagequeue/messagequeue.go
messagequeue/messagequeue_test.go
peermanager/peermanager.go
peermanager/peermanager_test.go
testutil/testutil.go
wantlist/wantlist.go
wantlist/wantlist_test.go
wantmanager/wantmanager.go
wantmanager/wantmanager_test.go

Make handling of wantlists more clear, avoid memory copying with session tracking, remove unneeded mutexes
Currently, the wantlist code obscures multiple different concerns:
- tracking of sessions (only needed for our own wantlists and our own outgoing wantlists for individual peers)
- thread safety
- bookkeeping fields only needed for incoming peer wantlists
All of this is made worse by the fact that every field on a wantlist entry becomes a field on a Bitswap message entry, even though they are unused
This PR takes the following approach:
- cut the wantlist public fields down to the ones that are used universally - CID & Priority
- handle thread safety outside the wantlist itself, since it's already largely handled that way
- move session tracking to private fields in a session tracked …

More specific wantlists

---

decision/bench_test.go
decision/engine.go
decision/ledger.go
decision/peer_request_queue.go
decision/peer_request_queue_test.go
message/message.go
wantlist/wantlist.go
wantlist/wantlist_test.go
wantmanager/wantmanager.go

This is probably a drop in the bucket but we allocate quite a few of these so we might as well make this as efficient as possible.

Avoid allocating for wantlist entries

---

messagequeue/messagequeue.go
peermanager/peermanager.go
peermanager/peermanager_test.go
testutil/testutil.go
wantmanager/wantmanager.go
wantmanager/wantmanager_test.go

1. Remove indirection from `bsmsg.Entry`.
2. Use a pool for `AddMessage` messages. This showed up in a pprof allocation count profile (top 5) while pinning.

remove allocations round two

---

providerquerymanager/providerquerymanager.go
providerquerymanager/providerquerymanager_test.go

I've added a few tests but we should probably prioritize bitswap test coverage in the near future.

fix(prq): fix a bunch of goroutine leaks and deadlocks

---

messagequeue/messagequeue.go

Ideally, fix #92
Revert to the old go-routine architecture for the messagequeue.
I originally setup the second go-routine because I believed I needed to block access to the wantlist inside a go-routine, which no longer has a mutex. however, I now see that the lock that was previously used for building the outgoing message actually covers all cases where the wantlist is modified. At minimum, it can't hurt to revert to previous setup and remove the loop that is causing so many problems. It is difficult to tell if the problem however is related to the loop itself or just sending more messages.
This does pass go test --race FWIW.

fix(messagequeue): Remove second run loop

---

providerquerymanager/providerquerymanager.go

This can happen even when everything is working correctly.
fixes https://github.com/ipfs/go-ipfs/issues/6046

fix: remove non-error log message

---

workers.go

Goprocess returns a _custom_ context type. Unfortunately, golang has a bunch of magic type assertions to efficiently handle built-in context types but launches a new goroutine when deriving a new context from a custom context type. Otherwise, it has no way to wait on the custom context's channel.
This fix just ensures we only ever have one of goroutines per provide worker by deriving a (normal) cancelable context up-front and then using that.

fix: limit use of custom context type

---

go.mod
go.sum
notifications/notifications.go
package.json

In preparation for switching over to go modules entirely. We no longer need our
fork.

dep: switch back to upstream pubsub

---

network/ipfs_impl.go

This reverts commit fc1278e68095a1d8f367ea4b37a571a0a137d65c.
It appears that using a buffer here is no longer necessary after the
upstream fix https://github.com/gogo/protobuf/pull/504
The `bufio.NewWriter` looks to be responsible for nearly half the allocations (by size) on a heavily loaded ipfs daemon:
```
(pprof) peek msgToStream
Showing nodes accounting for 193647.89MB, 100% of 193647.89MB total
----------------------------------------------------------+-------------
flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
92608.33MB   100% |   gx/ipfs/QmcSPuzpSbVLU6UHU4e5PwZpm4fHbCn5SbNR5ZNL6Mj63G/go-bitswap/network.(*streamMessageSender).SendMsg
7.47MB 0.0081% | …
```

Reduce memory allocation

---

bitswap.go

This'll back up the queue but take a large load off the DHT.

reduce provide workers to 6

---

messagequeue/messagequeue.go
messagequeue/messagequeue_test.go

Provide a failsafe to losing wants on other end by rebroadcasting a wantlist every thirty seconds
Every peer messagequeue has a rebroadcast timer, which, when it expires, resends all the wants. On the other hand, existing logic in the decision engine will dedup these wants if they are already queued up (see peer request queue)
What's the right interval? I set 30 seconds as a start --- seems long enough to so that there won't be a ton of new network traffic, but short enough that a lost want doesn't mean a super extra long recovery
Do we need something smarter? Or is just rebroadcasting at a regular interval ok? I would be inclined to try this to start, and do something smarter (like rebroadcast if wants sit on the list a long time) later.
fix #99, fix #65

feat(messagequeue): rebroadcast wantlist

---

bitswap.go
go.mod
go.sum

* HasBlockBufferSize and provideKeysBufferSize no longer matter as we have an
infinite in-memory buffer.
* provideWorkersMax now defaults to 6 so changing this to 16 actually _increases
memory consumption.

remove IPFS_LOW_MEM flag support

---

bitswap.go
bitswap_test.go
peermanager/peermanager.go
wantmanager/wantmanager.go
wantmanager/wantmanager_test.go

make the WantlistManager own the PeerHandler

---

bitswap.go
decision/engine.go
peermanager/peermanager.go
sessionpeermanager/sessionpeermanager.go

Review as individual commits, the other two commits are chores.

connmgr: give peers more weight when actively participating in a session

---

bitswap.go
bitswap_test.go
workers.go

We are working on removing the providing behavior from `go-bitswap` and putting it into its own module in `go-ipfs`. At first the feature will be experimental, and so this commit allows us to disable the provide announcements by setting `bitswap.ProvideEnabled` to `false` before creating bitswap. The default value is `true`.

Control provider workers with experiment flag

---

decision/peer_request_queue.go
decision/peer_request_queue_test.go

Remove memory leak by making sure when request queues are idle that they are removed
fix #112
Unfortunately, cause the peer request queue uses a PriorityQueue which only has a Pop method (and no Remove method) the only point you can remove a partner is the moment it's already popped off the priority queue before you put it back on. This adds code to check and remove the partner. Also since partners do not have a peer ID you have to do an O(N) search through the list of active partners to find the peer ID -- I don't forsee this happening so much that it's necessary to improve but it could be added.
Also adds a test to make sure it happens
- Is this the memory leak you're thinking of in #112?
- Does this approach make sense?
- Does the remove need to be optimized by adding the peer id to …

fix(decision): cleanup request queues

---

network/ipfs_impl.go
network/ipfs_impl_test.go

Fix #125
Adds a mutex to the network interface default implementation's receiver member. This appears to be the source of the data races in #125. While it's not totally clear if this covers all of the race conditions, it clearly something that should happen, since receiver is referenced repeatedly across multiple goroutines. Also adds a nil check to the notification methods.

fix(network): add mutex to avoid data race

---

bitswap.go
bitswap_test.go
bitswap_with_sessions_test.go
session/session.go
session/session_test.go
sessionmanager/sessionmanager.go
sessionmanager/sessionmanager_test.go

Attempt to kill two birds with one stone:
1. Don't keep making requests for more providers for the same block (even thought they are already deduped in the provider query manager, still fires off a spurious go-routine in the SessionPeerManager) (#107 )
2. Periodically search for more providers (#95 )
Start tracking whether a tick is "consecutive" -- i.e no new unique blocks have been received since the last tick. On consecutive ticks do two things different:
1. Don't kick off another request for providers
2. Gradually back off the time till the next tick -- cause each tick rebroadcasts the whole want list, which is often expensive. Multiple consecutive ticks essentially mean whatever the session is being used for has largely stalled, so minimize usage just for this.
It might be a problem …

feat(sessions): add rebroadcasting, search backoff

---

bitswap.go
wantmanager/wantmanager.go

Enchanced logging for bitswap

---

go.mod
go.sum
message/message.go
network/ipfs_impl.go

depends on https://github.com/libp2p/go-msgio/pull/15

aggressively free memory

---

bitswap.go
session/session.go
session/session_test.go
sessiondata/sessiondata.go
sessionmanager/sessionmanager.go
sessionmanager/sessionmanager_test.go
sessionpeermanager/latencytracker.go
sessionpeermanager/peerdata.go
sessionpeermanager/sessionpeermanager.go
sessionpeermanager/sessionpeermanager_test.go
sessionrequestsplitter/sessionrequestsplitter.go
sessionrequestsplitter/sessionrequestsplitter_test.go
testutil/testutil.go

Track the speeds between session peers more accurately
The current SessionPeerManager uses a very simple algorithm for sorting peers by optimization -- it simply orders them by last block received.
This algorithm attempts to actually track peers length of time to respond to requests, and sort them not only by which is fastest, by provide useful information (and optimization rating from 1-0, with 1 being the fastest peer) about how they relate to each other.
The steps are as follows:
1. For a broadcast request, track all responses (not just first one) until a preset timeout period (5 seconds for now) and use that to establish optimization ratings between peers
2. For targeted requests, individually measure time for each peer requested up to a timeout period. If response is received, track …

Feat: Track Session Peer Latency More Accurately

---

sessionpeermanager/sessionpeermanager.go
sessionpeermanager/sessionpeermanager_test.go

May be the cause of https://github.com/ipfs/go-bitswap/issues/162

fix: memory leak in latency tracker on timeout after cancel

---

network/ipfs_impl.go
network/options.go

I need multiple bitswap instances on one libp2p node, this allows me to make bitswap use strings like `/myproto/ipfs/bitswap/1.1.0` for protocols.

network: Allow specifying protocol prefix

---

bitswap.go
decision/engine.go
getter/getter.go
notifications/notifications.go
session/session.go
session/session_test.go
sessionmanager/sessionmanager.go
sessionmanager/sessionmanager_test.go

This will enable us to pass around CIDs instead of Blocks (Fixes https://github.com/ipfs/go-bitswap/issues/173)

Refactor: use global pubsub notifier

---

sessionpeermanager/sessionpeermanager.go
sessionpeermanager/sessionpeermanager_test.go

Test: fix flakey session peer manager tests

---

bitswap.go
bitswap_test.go
session/session.go
session/session_test.go
session/sessionwants.go
session/sessionwants_test.go
sessionmanager/sessionmanager.go
sessionmanager/sessionmanager_test.go
wantmanager/wantmanager.go

Fix: don't ignore received blocks for pending wants

---

decision/engine.go
decision/engine_test.go
decision/ewma.go
decision/ledger.go
go.mod

This patch tracks two usefulness metrics: short-term usefulness and long-term usefulness. Short-term usefulness is sampled frequently and highly weights new observations. Long-term usefulness is sampled less frequently and highly weights on long-term trends.
In practice, we do this by keeping two EWMAs. If we see an interaction within the sampling period, we record the score, otherwise, we record a 0. The short-term one has a high alpha and is sampled every shortTerm period. The long-term one has a low alpha and is sampled every longTermRatio*shortTerm period.
To calculate the final score, we sum the short-term and long-term scores then adjust it ±25% based on our debt ratio. Peers that have historically been more useful to us than we are to them get the highest score.
The number of …

engine: tag peers based on usefulness

---

bitswap.go
decision/blockstoremanager.go
decision/blockstoremanager_test.go
decision/engine.go
decision/engine_test.go

Fixes https://github.com/ipfs/go-bitswap/issues/187
Combines experiments to improve read latency:
- [Parallelize request queue reads](https://github.com/ipfs/go-bitswap/pull/212)
Use several engine task workers to pull requests off the request queue
- [Parallelize blockstore reads](https://github.com/ipfs/go-bitswap/pull/213)
Use a pool of worker threads to read from the blockstore
See [results with simulated blockstore delay of 20ms](https://github.com/ipfs/go-bitswap/pull/215#issuecomment-545927131)

Parallelize engine reads

---

internal/peermanager/peermanager.go
internal/peermanager/peermanager_test.go

When a peer disconnected, the PeerManager was incorrectly informing all sessions that *all* peers had disconnected

Fix bug with signaling peer availability to sessions

---

go.mod
go.sum
internal/messagequeue/messagequeue.go

Unfortunately, this is one of those cases in go where abstractions hurt more than they help.
This:
* Makes it easy to send immediately if we wait too long and/or if we have enough to send.
* Is significantly more efficient than the debounce library as it doesn't spin off a bunch of "after" timers.
fixes #245

feat: debounce wants manually

---

internal/session/sessionwantsender.go
internal/session/sessionwantsender_test.go

Fixes https://github.com/ipfs/go-bitswap/issues/257
A potential issue I see with this simplistic approach is that if for example we are downloading a big file, the DAG will be split into many subbranches, so if for example
- there are two peers
- the DAG is split into two sub-branches from the root
- peer A has all blocks
- peer B has one sub-branch with half the leaf blocks
In this case a situation may arise where
- peer B will repeatedly respond with DONT_HAVE at the beginning
- peer B's consecutive DONT_HAVE limit will be exceeded
- peer B will be removed from the session
If peer B's latency was lower than peer A, then it would have been faster to keep peer B in the session.
@Stebalien I'm not so familiar with the structure that is produced by chunking, is this likely to be a problem …

Prune peers that send too many consecutive DONT_HAVEs

---

internal/session/sessionwantsender.go

When a peer sends us several consecutive DONT_HAVEs, we remove it from the session by calling `spm.SignalAvailability(p, false)`.
However inside that method we add the update to a channel. If the channel is already full from other updates then the call will block, bringing the run loop to a deadlock.
The solution is to put the call inside a go routine. Peers sending several consecutive DONT_HAVEs is an infrequent enough scenario that it shouldn't be too expensive to use a go-routine here.

Fix possible deadlock scenario in session want sender

---

bitswap_with_sessions_test.go
internal/messagequeue/messagequeue.go
internal/session/session.go
internal/session/session_test.go
internal/session/sessionwantsender.go
internal/session/sessionwantsender_test.go
workers.go

Fixes https://github.com/ipfs/go-bitswap/issues/259

Ensure broadcast when remaining peer becomes unavailable

---

bitswap_test.go
internal/decision/engine.go
internal/decision/engine_test.go
internal/messagequeue/donthavetimeoutmgr_test.go
internal/messagequeue/messagequeue_test.go
internal/session/sessionwantsender_test.go

Fixes https://github.com/ipfs/go-bitswap/issues/278

fix: races in tests

---

bitswap.go
internal/messagequeue/donthavetimeoutmgr.go
internal/messagequeue/messagequeue.go
internal/session/session.go

We should simulate a DONT_HAVE response when we send want-block to a peer and the peer doesn't respond within a reasonable amount of time.
We have this already for older peers (that don't support DONT_HAVE).
This PR adds support for newer peers (that do support DONT_HAVE).

Simulate DONT_HAVE when peer doesn't respond to want-block (new peers)

---

internal/session/session.go
internal/session/session_test.go
internal/session/sessionwants.go
internal/session/sessionwants_test.go

Fixes https://github.com/ipfs/go-bitswap/issues/290
- Limits the size of the list of wants that are broadcast on a Session idle tick
- Finds Providers of the first want for which a block has not been received (instead of a random want)

Fix order of session broadcast wants

---

bitswap.go
internal/peermanager/peermanager.go
internal/peermanager/peerwantmanager.go

And expose a separate function for _just_ getting want-blocks. When the user runs `ipfs bitswap wantlist`, they expect to see everything the node is currently looking for.

feat: expose the full wantlist through GetWantlist

---

internal/messagequeue/donthavetimeoutmgr.go
internal/messagequeue/donthavetimeoutmgr_test.go
internal/messagequeue/messagequeue.go

This removes one goroutine per peer which tends to be a pretty big deal. This brings go-ipfs down from 5.5 to 4.5 goroutines per peer.

feat: remove the context from the donthavetimeoutmanager

---

internal/decision/engine.go
internal/decision/engine_test.go
internal/decision/ledger.go
internal/messagequeue/messagequeue.go
internal/testutil/testutil.go
message/message.go
wantlist/wantlist.go

We send them as fixed-sized 32bit ints on the wire, so we don't need to store them locally as full ints.
This should bring each Entry down from 32 bytes to 24 bytes because the Priority and WantType should now fit into 8 bytes with no padding.
Is this super important? Probably not. But it is showing up in pprof (although most of the space is probably going to the underlying CIDs).

feat: micro-optimize priority

---

internal/session/sessionwantsender_test.go

Fixes https://github.com/ipfs/go-bitswap/issues/322

fix: flaky TestSendsWantBlockToOnePeerOnly

---

internal/session/session.go
internal/session/sessionwantsender.go
internal/session/sessionwantsender_test.go

This may help with https://github.com/ipfs/go-bitswap/issues/310
We need to test it in staging to be sure.

wait for sessionWantSender to shutdown before completing session shutdown

---

internal/peermanager/peermanager.go
internal/peermanager/peerwantmanager.go

Fixes https://github.com/ipfs/go-bitswap/issues/316

fix: log unexpected condition in peerWantManager.prepareSendWants()

---

internal/messagequeue/messagequeue.go

In case we're sending a _lot_ of wants:
* Prioritize cancels.
* Then targeted wants.
* Finally broadcast wants.

feat: prioritize more important wants

---

network/ipfs_impl.go

There's no reason to launch this async.

fix: avoid goroutine when receiving an error

---

internal/decision/engine.go
internal/decision/ledger.go
internal/messagequeue/messagequeue.go
internal/messagequeue/messagequeue_test.go
internal/peermanager/peermanager.go
internal/peermanager/peermanager_test.go
network/connecteventmanager.go
network/connecteventmanager_test.go
network/interface.go
network/ipfs_impl.go
network/ipfs_impl_test.go
testnet/virtual.go

Part of the fix for https://github.com/ipfs/go-bitswap/issues/347

Move connection management into networking layer

---

internal/messagequeue/messagequeue.go
message/message.go

Fixes https://github.com/ipfs/go-bitswap/issues/352

feat: optimize entry sorting in MessageQueue

---

go.mod
internal/decision/engine.go
internal/messagequeue/messagequeue.go
message/message.go
wantlist/wantlist.go
wantlist/wantlist_test.go

Instead of holding the lock the entire time we prepare a message, hold the lock while we retrieve the wantlist entries, process the entries without the lock, retake the lock, then mark entries as sent.
This means:
1. We never sort entries while holding the lock.
2. We allocate exactly three times while holding the lock (once per entry list).
This change also tries to be as lazy as possible when sorting.

fix: minimize time holding wantlist lock

---

internal/messagequeue/messagequeue.go
internal/peermanager/peermanager.go
internal/peermanager/peermanager_test.go
internal/peermanager/peerwantmanager.go
internal/peermanager/peerwantmanager_test.go
internal/wantmanager/wantmanager.go
internal/wantmanager/wantmanager_test.go

This deduplicates some state and allows us to do less book-keeping for broadcast wants. We should probably rename the PeerManager to the WantManager and rename the WantManager to something else. It no longer manages _any_ wants.

feat: move broadcast wantlist into the peermanager

---

network/ipfs_impl.go

Fixes https://github.com/ipfs/go-bitswap/issues/367

fix: avoid calling ctx.SetDeadline() every time we send a message

---

internal/messagequeue/donthavetimeoutmgr.go

Ideally we would actually measure how long it takes between sending a want and receiving a response, but this will solve the immediate problem of too many dups

Change timing for DONT_HAVE timeouts to be more conservative

---

bitswap.go
internal/session/session.go
internal/session/session_test.go

When the session's context is done, the session sends CANCELs for all pending wants.
However it uses the same (done) context to send the CANCELs, so they never actually get sent.
This PR changes the session to use Bitswap's context to send CANCELs on shutdown.

Send CANCELs when session context is cancelled

---

bitswap.go
bitswap_with_sessions_test.go
internal/messagequeue/donthavetimeoutmgr.go
internal/messagequeue/donthavetimeoutmgr_test.go
internal/messagequeue/messagequeue.go
internal/messagequeue/messagequeue_test.go
internal/peermanager/peermanager.go
internal/peermanager/peermanager_test.go

Fixes https://github.com/ipfs/go-bitswap/issues/385

calculate message latency

---

internal/decision/engine.go
internal/decision/engine_test.go

Note: this is causing interop test failures

fix: return wants from engine.WantlistForPeer()

---

internal/peermanager/peermanager.go
internal/peermanager/peermanager_test.go
internal/peermanager/peerwantmanager.go
internal/peermanager/peerwantmanager_test.go

Fixes https://github.com/ipfs/go-bitswap/issues/392
Roughly 4x improvement with a somewhat contrived benchmark:
```
$ go test ./internal/peermanager -run xyz -v -bench . -benchtime 5s
goos: darwin
goarch: amd64
pkg: github.com/ipfs/go-bitswap/internal/peermanager
BenchmarkPeerManager
BenchmarkPeerManager-8   	   40218	    148840 ns/op
$ go test ./internal/peermanager -run xyz -v -bench . -benchtime 5s
cpu.out
goos: darwin
goarch: amd64
pkg: github.com/ipfs/go-bitswap/internal/peermanager
BenchmarkPeerManager
BenchmarkPeerManager-8   	  182610	     33038 ns/op
```

Improve peer manager performance

---

internal/peermanager/peermanager.go
internal/peermanager/peerwantmanager.go
internal/peermanager/peerwantmanager_test.go

Fixes https://github.com/ipfs/go-bitswap/issues/333
Currently we track the number of pending want-blocks in `wantlist_total`.
In this PR
- `wantlist_total` is the total number of pending want-blocks + want-haves
- `want_blocks_total` is the total number of pending want-blocks

Total wants gauge

---

internal/session/session.go
internal/session/session_test.go
internal/session/sessionwantsender.go
internal/session/sessionwantsender_test.go
internal/sessionmanager/sessionmanager_test.go
internal/sessionpeermanager/sessionpeermanager.go
internal/sessionpeermanager/sessionpeermanager_test.go

When receiving blocks, if the peer that sent the block was the first to send it, protect the connection to the peer, so that it doesn't get pruned by the connection manager.

If peer is first to send a block to session, protect connection

---

.circleci/config.yml
internal/peermanager/peermanager.go
internal/session/session.go
internal/session/session_test.go
internal/session/sessionwantsender_test.go
internal/sessionmanager/sessionmanager_test.go

Or, really, just avoid accessing it. We don't need it.
This caused a concurrent map access panic under load.

fix: avoid taking accessing the peerQueues without taking the lock

---

internal/decision/engine.go

I'm not sure why we set "full" to true here, but this could be the source of a whole bunch of bidirectional sync issues. That is, if two peers are syncing off each other, they could repeatedly "reset" each other's wantlist to "empty".

fix: don't say we're sending a full wantlist unless we are

---

bitswap.go
bitswap_test.go
decision/decision.go
internal/decision/engine.go
internal/decision/engine_test.go
internal/decision/ledger.go
internal/decision/scoreledger.go

First, I've separated the decision engine ledger on two parts: score and the wantlist. The wantlist still resides in the original `ledger` struct while sent/received byte accounting and scores are extracted to the new `scoreledger` struct managed by the original `scoreWorker()` logic. The accounting is integrated into the `Engine` via `ScoreLedger` interface making it possible to replace the original `scoreWorker()` with some other logic. The interface, however, doesn't allow a score logic to directly touch peer tags: the logic may decide about score values while tagging itself is still under control of Engine.
Then I've added new `WithScoreLedger(decision.ScoreLedger)` option in the `bitswap` package is the way to connect a custom `ScoreLedger` implementation to the decision engine. The …

Added `WithScoreLedger` Bitswap option 

---

network/ipfs_impl.go
network/ipfs_impl_test.go

Fix: Increment stats.MessagesSent in msgToStream() function

---

bitswap.go
bitswap_test.go
wiretap.go
workers.go

WireTap interface can be used to access all messages send and received
by Bitswap. This can be used to implement advanced statistics/analysis
logic, which is beyond scope of Bitswap, but can be implemented as IPFS
plugin.
Some examples of potential applications:
- per CID bandwidth tracker (see: https://gitcoin.co/issue/PinataCloud/apollo/2/100023631)
- detailed per peer stats
- intrusion detection system (IDS) implementation
I tried to implement the entire "tapping" mechanism in the least obstructing way.
Because entire messages are passed for external processing, range of possible applications is enormous.
I created PR (without prior issue), because change is small and _a commit is worth a thousand words_ ;)

Add WireTap interface

---

internal/decision/engine.go
internal/decision/scoreledger.go

It's possible to start receiving and processing messages before we get around to starting.

fix: set the score ledger on start

---

bitswap.go
internal/decision/blockstoremanager.go
internal/decision/blockstoremanager_test.go
internal/decision/engine.go
internal/decision/engine_test.go

Fixes https://github.com/ipfs/go-bitswap/issues/448

Configurable engine blockstore worker count

---

internal/decision/blockstoremanager.go

fix a startup race by creating the blockstoremanager process on init

---

bitswap_test.go
internal/decision/engine_test.go
internal/messagequeue/messagequeue.go
internal/messagequeue/messagequeue_test.go
network/ipfs_impl_test.go

context: https://github.com/protocol/.github/issues/41

fix staticcheck

---

network/ipfs_impl.go

See https://github.com/ipfs/go-ipfs/issues/7972#issuecomment-824327775 for background.
If there is a straightforward 10-line way to test this I can add it, otherwise I'll just leave the fix.

fix(network): impl: add timeout in newStreamToPeer call

---

testnet/virtual.go

This needs to be at the top of the "allocated" struct. Otherwise, 32bit tests fail.

fix: fix alignment of stats struct in virtual network

---

go.mod
go.sum
internal/decision/engine_test.go
internal/decision/scoreledger.go

fix #472
Start to fix flaking timing tests by mocking out time.

fix flaky TestTaggingUseful test

---

network/ipfs_impl.go

Fix TestNetworkCounters flakiness
part of fixing #493 
The problem is just a race in counting messages, and I've dealt with that by moving the counting to immediately before the call that advances the test. I don't think it's relevant to Bitswap execution otherwise.

Fix flaky TestNetworkCounters tests

---

bitswap.go
bitswap_with_sessions_test.go

fix #442
The TestSessionWithPeers test was most commonly failing cause of a don't
have timeout, which triggered simulated don't have message for all CIDs
on the peer with content, which triggered a re-broadcast, causing peers
with no content to receive additional wants.
This PR adds an option to not send these simulated don't have messages in tests.

Fix TestSessionWithPeers flakiness

---

bitswap.go
bitswap_with_sessions_test.go
go.mod
go.sum
internal/decision/engine_test.go
internal/decision/scoreledger.go
internal/messagequeue/donthavetimeoutmgr.go
internal/messagequeue/donthavetimeoutmgr_test.go
network/ipfs_impl.go

Fix flaky tests for the DontHaveTimeoutManger
Replace clock with a mock, so that we are able to mock out time in tests, modify tests to use mock time and be more predictable.
Also avoid AfterFunc cause of potential problems with channel consumption.

Fix flaky DontHaveTimeoutManger tests

---

internal/messagequeue/donthavetimeoutmgr.go
internal/messagequeue/messagequeue.go
internal/messagequeue/messagequeue_test.go

Fix all the flaky tests of the message queue
Once again, errors come down to timing, and I'm fixing by mocking time in flaky tests
In this case, I didn't actually go and replace all the tests, as this would be a big endeavor
part of #493

Fix flaky tests in message queue

---

bitswap.go

This option is used by the benchmark to simulate the old bitswap comportement (and fixes the benchmark).
This follows the same refactoring idea as done in 47b99b1ce34a.
It was crashing since it was trying to access the `sendDontHaves` property of `bs.engine` but `bs.engine` is initialized right after the options are applied, not before.
Unlike 47b99b1ce34a, I've choosed to not make `sendDontHaves` part of engine's constructor because this is such an obscure option, useless in +99% of realworld scenario that it's not needed to confuse the engine contructor.

fix: Nil dereference while using SetSendDontHaves

---

internal/decision/engine.go

Otherwise, we could try to shutdown at the same time and race.

fix: hold the task worker lock when starting task workers

---

internal/decision/engine.go

We need to hold the ledger's lock while reading from it.

fix(decision): fix a datarace on disconnect

---

internal/decision/engine.go

We should have better tests here, but I'm not sure how to go about that. We basically need a fuzzer.

fix: fix a map access race condition in the want index

---

internal/decision/engine.go

These log messages are frequent and were causing lock contention at scale.

fix: reduce log verbosity

---

network/connecteventmanager.go

fix: fix race on "responsive" check

---

bitswap.go
internal/decision/engine.go
internal/decision/engine_test.go

This feature lets a user configure a filter to allow / deny request according to the request's peer ID and the content id.
For example, a user may use this option to implement a dynamic peer-based authorization.

feat: add peer block filter option

---

bitswap.go
network/connecteventmanager.go
network/connecteventmanager_test.go
network/interface.go
network/ipfs_impl.go
network/ipfs_impl_test.go
testnet/network_test.go
testnet/virtual.go

This change handles connectedness and responsiveness events asynchronously, coalescing multiple state-changes into one. In the past, this area has caused quite a bit of goroutine buildup as we fall behind processing connect and disconnect events.
The design is a simple state-machine with the following components:
1. A record of the current and "new" state for each peer.
2. A queue of peers that have "changed".
3. A worker that applies state transitions.
1. When an event (disconnect, connect, unresponsive, responsive) happens, we record the _desired_ (new) state for that peer and enqueue the peer for further processing by the background worker.
2. The background worker takes peers off the background task queue, applying state-changes.
Importantly:
1. There's only one background worker. …

feat: coalesce and queue connection event handling

---

bitswap_test.go

This will be necessary when we start updating deps since we removed this: https://github.com/libp2p/go-libp2p-testing/pull/57

Remove dependency on travis package from go-libp2p-testing

---

bitswap.go
bitswap_test.go
bitswap_with_sessions_test.go
go.mod
go.sum
internal/decision/engine.go
internal/decision/engine_test.go
internal/notifications/notifications.go
version.json

This leave the responsibility and choice to do so to the caller, typically go-blockservice.
This has several benefit:
- untangle the code
- allow to use an exchange as pure block retrieval
- avoid double add
Close https://github.com/ipfs/kubo/issues/7956

Don't add blocks to the datastore
